'use strict';

const gulp = require('gulp'),
      gulpConcat = require('gulp-concat'),
      gulpInsert = require('gulp-insert');

const spawn = require('child_process').spawn;

const config = {
  jsPaths: [
    './assets/js/jquery.min.js',
    './assets/js/jquery.scrollex.min.js',
    './assets/js/jquery.scrolly.min.js',
    './assets/js/skel.min.js',
    './assets/js/util.js',
    './assets/js/main.js',
  ]
}

const warningBanner = `/*******************************************************************************
* CAUTION!  DO NOT EDIT THIS FILE!                                             *
*                                                                              *
* This file was generated automatically, and any changes made to it will be    *
* overwritten.  Please do not edit it directly.                                *
*******************************************************************************/

`;

function buildScripts() {
  return Promise.resolve();
}

function watchScripts() {
  gulp.watch('./assets/js/**/*', buildScripts);
}

function buildStyles() {
  return gulp.src(config.jsPaths)
    .pipe(gulpConcat('main.js'))
    .pipe(gulpInsert.prepend(warningBanner))
    .pipe(gulp.dest('./assets/'));
}

function watchStyles() {
  gulp.watch('./assets/css/**/*', buildStyles);
}

function runServer() {
  return spawn('node', ['../../../index.js'], {stdio: 'inherit'});
}

const buildAssets = gulp.parallel(buildScripts, buildStyles);

const watchAssets = gulp.parallel(watchScripts, watchStyles);

gulp.task('build', buildAssets);

gulp.task('serve', gulp.series(
  buildAssets,
  gulp.parallel(
    watchAssets,
    runServer
  )
));
